services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "16379:6379"   # đổi từ 6379 -> 16379
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"   # đổi từ 8080 -> 18080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docsEngine?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: collabpass
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-PZQhbm2pxG2uTlbcHMxwTB4amG59/+uK+nYbCV/4u4o=}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "13000:80"   # đổi từ 3000 -> 13000
    depends_on:
      - backend
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: docsEngine
      MYSQL_ROOT_PASSWORD: collabpass
    ports:
      - "33306:3306" # Đổi cổng ngoài để tránh trùng nếu máy bạn đã có MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pcollabpass"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgres_data: # giữ lại volume cũ nếu cần, hoặc xóa đi
  mysql_data: